name: Publish to Confluence
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: markdown-confluence
        uses: markdown-confluence/publish-action@v5
        with:
          atlassianApiToken: ${{ secrets.atlassianApiToken }}
          configFile: .markdown-confluence.json